### ISSUE TITLE
SNAT exhaustion on Azure / Github Actions

### ISSUE THREAD

**Issue by Lykathia** [jfrog/jfrog-client-go#195]
Hey all,

It appears that due to the [`leaveBodyOpen`](https://github.com/jfrog/jfrog-client-go/blob/7727f02b0b3f2da394c3c20aa4a464c8aa5a8078/httpclient/client.go#L31) style functions, ports aren't getting reused and causing [SNAT port exhaustion](https://docs.microsoft.com/en-us/azure/load-balancer/troubleshoot-outbound-connection#snatexhaust) when being run w/ a large number of requests on AzDO or GHA.

Specifically, I came across this while trying to run a npm install from the jfrog cli, w/ build metadata enabled. Since there is an individual AQL call made for every single dependency to retrieve the checksum for said dependency - it quickly saturates the ports and causes a TCP timeout.

I had looked @ fixing this by writing 'better' AQL in the jfrog CLI, but it appears to cause a segfault on the Artifactory server side due to payload being too large. So instead I started tracking down the network calls, and was led here.

A brief search thru the git history didn't appear to turn up anything -- I'm wondering what the use case for the 'leave body open' connections is? An easy fix would be to not use it - this is certainly a hindrance for any NPM style builds w/ build-info enabled.

**Comment by eyalbe4** [comment]
@Lykathia,
Thanks for the deep drill down into the code!
I think you are correct and may have found the root cause of the issue. The issue seems to related to a massive refactor which both the ```jfrog-client-go``` and ```jfrog-cli``` projects went through recently. The fix for this issue should be on the ```jfrog-cli``` code base only though, because body of the request should probably be closed there.
The reason why the body is left open, is to allow the API which sent the request to read the body and then close it.
I suspect that code with the missing ```close()``` is below. Notice the ```defer stream.Close()``` - it is missing with the latest released code. I think this should fix the issue.
```
// Creates a function that fetches dependency data from Artifactory. Can be applied from a producer-consumer mechanism
func (nca *NpmCommandArgs) createGetDependencyInfoFunc(servicesManager *artifactory.ArtifactoryServicesManager) getDependencyInfoFunc {
	return func(dependencyIndex string) parallel.TaskFunc {
		return func(threadId int) error {
			name := nca.dependencies[dependencyIndex].name
			ver := nca.dependencies[dependencyIndex].version
			log.Debug(clientutils.GetLogMsgPrefix(threadId, false), "Fetching checksums for", name, "-", ver)
			stream, err := servicesManager.Aql(serviceutils.CreateAqlQueryForNpm(name, ver))
			if err != nil {
				return err
			}
			defer stream.Close()
			result, err := ioutil.ReadAll(stream)
			if err != nil {
				return err
			}
			parsedResult := new(aqlResult)
			if err = json.Unmarshal(result, parsedResult); err != nil {
				return errorutils.CheckError(err)
			}
			if len(parsedResult.Results) == 0 {
				log.Debug(clientutils.GetLogMsgPrefix(threadId, false), name, "-", ver, "could not be found in Artifactory.")
				return nil
			}
			nca.dependencies[dependencyIndex].artifactName = parsedResult.Results[0].Name
			nca.dependencies[dependencyIndex].checksum =
				&buildinfo.Checksum{Sha1: parsedResult.Results[0].Actual_sha1, Md5: parsedResult.Results[0].Actual_md5}
			log.Debug(clientutils.GetLogMsgPrefix(threadId, false), "Found", parsedResult.Results[0].Name,
				"sha1:", parsedResult.Results[0].Actual_sha1,
				"md5", parsedResult.Results[0].Actual_md5)
			return nil
		}
	}
}
```
It appears that this issue requires an immediate fix. We will issue a patch soon!

**Comment by Or-Gabay** [comment]
@Lykathia, JFrog-CLI 1.39.3 is released and includes a fix for this issue.
Feel free to update your JFrog-CLI and share your feedback.

**Comment by Lykathia** [comment]
@Or-Gabay this does not fix the issue, ports are still held open w/ exhaustion on all the ports, resulting in a TCP timeout.

@eyalbe4 I think I would have looked @ fixing the code here, using a functional closure to do the work inside the scope of the function being executed, instead of pushing responsibility for closure back up the stack. Or alternatively, doing an IO copy, closing the connection, and passing the data back up the stack.
Dealing with all the pointers/references/threads across multiple go libraries seems like a more difficult problem then I would want to tackle! :D

**Comment by Lykathia** [comment]
Some different thoughts that floated to mind:
Batching queries, to make less roundtrips, or putting in retries on failure.

Doesn't solve the TCP stuff directly, but does increase the overall robustness of the functionality in other ways (that would mitigate SNAT exhaustion possibilities).

**Comment by eyalbe4** [comment]
@Lykathia,
Can you please confirm that you are using version 1.39.3 by running ```jfrog -v```?
Also, does this issue disappear with version 1.38.4?

**Comment by Lykathia** [comment]
@eyalbe4 yep, I confirmed it was 1.39.3 before posting. But for completing the circle:

![image](https://user-images.githubusercontent.com/1256508/92199155-ba5fff00-ee4c-11ea-913d-b36eb5edf610.png)

Versions I have observed this issue with:
1.35.5
1.37.1
1.38.2
1.38.4
1.39.3

**Comment by eyalbe4** [comment]
Thanks for this information @Lykathia.
This means the issue is not related to the recent changes. We'll try reproducing this with GitHub Actions. Are you using a hosted agent? Which type?

**Comment by Lykathia** [comment]
```
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Jfrog CLI
        uses: jfrog/setup-jfrog-cli@v1
        with:
          VERSION: 1.39.3
        env:
          JF_ARTIFACTORY_1: ${{ secrets.ARTIFACTORY_CONFIG }}

      - name: Install Dependencies
        run: |
          jfrog rt npmc --server-id-resolve ${{ env.ARTIFACTORY_SERVER }} --server-id-deploy ${{ env.ARTIFACTORY_SERVER }} --repo-resolve npm --repo-deploy ${{ env.ARTIFACTORY_BUCKET }}
          jfrog rt npmci
        env:
          JFROG_CLI_BUILD_NAME: ${{ github.repository }}
```
